### PR TITLE
Port to jbuilder (dune)

### PR DESCRIPTION
**Pull request by rgrinberg**
The port is almost. I just need to port the tests, but it's a bit tough to get the protobuf compiler running.

### CODE REVIEW

**Comment by rgrinberg** [comment]
@yallop are you also keeping this one >= 4.01? :) Some pointers with the tests would be appreciated.

**Comment by yallop** [comment]
@rgrinberg: no, this project inherits the `>= 4.03.0` constraint from Faraday, so there's no problem there.

What kind of pointers would be helpful?  You'll need `protoc` and the Python `protobuf` package installed; on Debian I use the `protobuf-compiler` package for `protoc`, and install the Python package via `pip`.

**Comment by rgrinberg** [comment]
Here's the current error I'm getting when running the tests:

```
      python lib_test/comprehensive.python.serialized,lib_test/small.python.serialized,lib_test/twostring.python.serialized (exit 1)
(cd _build/default/lib_test && /Users/rgrinberg/miniconda3/envs/ocamlpb/bin/python test_gen.py)
Traceback (most recent call last):
  File "test_gen.py", line 3, in <module>
    import test_pb2
  File "/Users/rgrinberg/reps/ml/ocaml-pb/_build/default/lib_test/test_pb2.py", line 23, in <module>
    n\x0erepeated_Small\x18& \x03(\x0b\x32\x06.Small\x12\x17\n\x0frepeated_double\x18\' \x03(\x01\x12\x17\n\x0frepeated_string\x18( \x03(\t\x12\x19\n\x11required_sfixed64\x18) \x02(\x10\x12\x17\n\x0frequired_sint64\x18* \x02(\x12\x12\x17\n\x0foptional_string\x18+ \x01(\t\x12\x17\n\x0foptional_uint32\x18, \x01(\r\x12\x19\n\x11repeated_sfixed32\x18- \x03(\x0f\x12\x16\n\x0eoptional_float\x18. \x01(\x02\x12\x17\n\x0foptional_uint64\x18/ \x01(\x04\x12\x1c\n\rrequired_enum\x18\x30 \x02(\x0e\x32\x05.Enum\x12\x17\n\x0frequired_sint32\x18\x31 \x02(\x11\x12\x18\n\x10required_fixed32\x18\x32 \x02(\x07\x12\x16\n\x0erepeated_int32\x18\x33 \x03(\x05*\x18\n\x04\x45num\x12\x07\n\x03one\x10\x01\x12\x07\n\x03two\x10\x02')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

I assume i'm using the wrong version of python or pb's?

**Comment by yallop** [comment]
It could be the wrong version of the Python protobuf library.  I'm using version 3.0.0:

```
$ python -c 'import google.protobuf as g; print g.__version__'
3.0.0
```

**Comment by yallop** [comment]
@rgrinberg: I've rebased this and updated from jbuilder to dune.  I'm happy to merge it once we have all the tests working.

**Comment by martinslota** [comment]
@rgrinberg @yallop I tried to finalize the changes here: https://github.com/rgrinberg/ocaml-pb/pull/1

**Comment by yallop** [comment]
Thanks @rgrinberg and @martinslota!

**Pull request merged**
